# Generated by Django 2.2.5 on 2022-04-21 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20190930_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Story'),
        ),
    ]
